version: "3"
services:
  lambda-clone:
    build: ./
    ports:
      - "8081:8081"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_DNS=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:7.0"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
