apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: lambda-clone
  name: lambda-clone-role
  namespace: default
rules:
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - update
      - delete
